CREATE TABLE PRICES (
	ID			BIGINT			auto_increment NOT NULL,
	BRAND_ID	BIGINT			NOT NULL,
	START_DATE	TIMESTAMP		NOT NULL,
	END_DATE	TIMESTAMP		NOT NULL,
	PRICE_LIST	INTEGER			NOT NULL,
	PRODUCT_ID	BIGINT			NOT NULL,
	PRIORITY	INTEGER			NOT NULL,
	PRICE		NUMERIC(20,2)	NOT NULL,
	CURR		VARCHAR(10)		NOT NULL,
	PRIMARY KEY(ID)
);